_BASE_: "../Base-RCNN-DilatedC5.yaml"
DATASETS:
  TRAIN: ('voc_2012_train_instance', 'sbd_9118_instance')
  PROPOSAL_FILES_TRAIN: ('datasets/proposals/mcg_voc_2012_train_instance_d2.pkl', 'datasets/proposals/mcg_sbd_9118_instance_d2.pkl')
  #TRAIN: ('sbd_9118_instance',)
  #PROPOSAL_FILES_TRAIN: ('datasets/proposals/mcg_sbd_9118_instance_d2.pkl',)
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 4000
  TEST: ('voc_2012_val_instance',)
  PROPOSAL_FILES_TEST: ('datasets/proposals/mcg_voc_2012_val_instance_d2.pkl', )
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 4000
