MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNWSL"
  RESNETS:
    OUT_FEATURES: ["res5"]
    RES5_DILATION: 2
  RPN:
    IN_FEATURES: ["res5"]
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "WSDDNROIHeads"
    IN_FEATURES: ["res5"]
    BATCH_SIZE_PER_IMAGE: 4096
    POSITIVE_FRACTION: 1.0
  ROI_BOX_HEAD:
    NAME: "DiscriminativeAdaptionNeck"
    NUM_FC: 2
    DAN_DIM: [4096, 4096]
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
